### ISSUE TITLE
Display an error message if OPENAI_API_KEY is missing.

### ISSUE THREAD

**Issue by kjrstory** [darrenburns/elia#24]
Elia must add an environment variable OPENAI_API_KEY. What if we check this in the code and display an error message if it's not in the environment variable?

I did a test for this. Firstly, I wanted to put the error check logic in the Elia function of app.py, but it didn't work properly.
The reason is that the imported library also needs OPENAI_API_KEY.
```
Traceback (most recent call last):
  File "/root/venvs/elia_fork/bin/elia", line 3, in <module>
    from elia_chat.__main__ import cli
  File "/root/projects/elia_fork/elia_chat/__main__.py", line 15, in <module>
    from elia_chat.app import Elia
  File "/root/projects/elia_fork/elia_chat/app.py", line 14, in <module>
    from elia_chat.models import EliaContext
  File "/root/projects/elia_fork/elia_chat/models.py", line 9, in <module>
    from elia_chat.widgets.chat_options import GPTModel, MODEL_MAPPING, DEFAULT_MODEL
  File "/root/projects/elia_fork/elia_chat/widgets/chat_options.py", line 44, in <module>
    model=ChatOpenAI(
  File "/root/venvs/elia_fork/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```

For this, the logic must be inserted in the middle of importing, is that okay?
```python
import os
from pathlib import Path
from typing import Optional

import openai
from textual.app import App

import sys, click

if not os.getenv("OPENAI_API_KEY"):
    click.echo("Error: OPENAI_API_KEY environment variable is not set.", err=True)
    sys.exit(1)

from elia_chat.models import EliaContext
from elia_chat.screens.chat_screen import ChatScreen
...
```

**Comment by darrenburns** [comment]
This is no longer relevant as of 1.0.0
