### ISSUE TITLE
No module named 'greenlet' after installing v1.0

### ISSUE THREAD

**Issue by adriangalilea** [darrenburns/elia#30]
```
❯ elia
Creating database at PosixPath('/Users/adrian/.local/share/elia/elia.sqlite')
Traceback (most recent call last):
  File "/Users/adrian/.local/bin/elia", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/elia_chat/__main__.py", line 57, in default
    create_db_if_not_exists()
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/elia_chat/__main__.py", line 29, in create_db_if_not_exists
    asyncio.run(create_database())
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/elia_chat/database/database.py", line 16, in create_database
    async with engine.begin() as conn:
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1063, in begin
    async with conn:
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
    return await self.start(is_ctxmanager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 273, in start
    await greenlet_spawn(self.sync_engine.connect)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 99, in greenlet_spawn
    _not_implemented()
  File "/Users/adrian/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/sqlalchemy/util/concurrency.py", line 79, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function. No module named 'greenlet'
```

Doing
`pipx inject elia-chat greenlet`

Fixed it.

**Comment by darrenburns** [comment]
Thanks! I've added the `greenlet` dependency to 1.0.1 - seems like it's a requirement for Apple Silicon.
