### ISSUE TITLE
Temperature set in config.toml being interpreted as int instead of float 

### ISSUE THREAD

**Issue by thorhojhus** [darrenburns/elia#45]
When using Groq with temperature different from 0.0 or 1.0 I get the following error:

```python
Traceback (most recent call last):
  File "/Users/thorh/.local/bin/elia", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/elia_chat/__main__.py", line 77, in default
    app = Elia(LaunchConfig(**launch_config), startup_prompt=joined_prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thorh/.local/pipx/venvs/elia-chat/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for LaunchConfig
models.0.temperature
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=0.4, input_type=float]
    For further information visit https://errors.pydantic.dev/2.7/v/int_from_float
```

**Comment by darrenburns** [comment]
Thanks - fixed in 1.6.1, which is now available.
