### ISSUE TITLE
Can't run local model.

### ISSUE THREAD

**Issue by Ji-Shao** [darrenburns/elia#65]
according the README.  to run local model, 
_"The location of the configuration file is noted at the bottom of the options window (ctrl+o)."_

"ctrl+o" didn't work on Linux.
How can I place the config file?

another issue:
If you don't export OPENAI_API_KEY, it won't start. even if you would like to use local model.

$ elia 
Traceback (most recent call last):
  File "/home/terx/.local/bin/elia", line 5, in <module>
    from elia_chat.__main__ import cli
  File "/home/terx/.local/share/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/__main__.py", line 10, in <module>
    from elia_chat.app import Elia
  File "/home/terx/.local/share/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/app.py", line 8, in <module>
    from elia_chat.models import EliaContext
  File "/home/terx/.local/share/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/models.py", line 9, in <module>
    from elia_chat.widgets.chat_options import GPTModel, MODEL_MAPPING, DEFAULT_MODEL
  File "/home/terx/.local/share/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/widgets/chat_options.py", line 44, in <module>
    model=ChatOpenAI(
  File "/home/terx/.local/share/pipx/venvs/elia-chat/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by darrenburns** [comment]
You're using an old version of Elia - hopefully this helps: https://github.com/darrenburns/elia/issues/56#issuecomment-2132438352
