### ISSUE TITLE
Does not run without `OPEN_AI_KEY` set

### ISSUE THREAD

**Issue by moberst** [darrenburns/elia#80]
I understand that setting a key is required, but for my use case (trying out with Gemini API key, but without an OpenAI API key), there are blockers to getting `elia` running.

To reproduce:
* Run the installation via `pipx install elia-chat` 
* Run `elia`, or `elia --help` or any similar command

Result:
```
Traceback (most recent call last):
  File "/home/moberst/.local/bin/elia", line 5, in <module>
    from elia_chat.__main__ import cli
  File "/home/moberst/.local/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/__main__.py", line 10, in <module>
    from elia_chat.app import Elia
  File "/home/moberst/.local/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/app.py", line 8, in <module>
    from elia_chat.models import EliaContext
  File "/home/moberst/.local/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/models.py", line 9, in <module>
    from elia_chat.widgets.chat_options import GPTModel, MODEL_MAPPING, DEFAULT_MODEL
  File "/home/moberst/.local/pipx/venvs/elia-chat/lib/python3.10/site-packages/elia_chat/widgets/chat_options.py", line 44, in <module>
    model=ChatOpenAI(
  File "/home/moberst/.local/pipx/venvs/elia-chat/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
  ```
  
It would be helpful to provide in the `README.md` instructions on how to configure without starting with OpenAI.  For instance, the README includes directions to use `ctrl+o` to see the location of the config file, but I cannot open the interface to get to that step.

I also notice that even when I set `export GEMINI_API_KEY=XXX` as an environmental variable, the same error occurs.

**Comment by darrenburns** [comment]
You've got an old version. I just updated the README with a new installation command:

```bash
pipx install --python 3.11 elia-chat
```

The latest versions require Python 3.11+. Hopefully that works for you.

**Comment by moberst** [comment]
Fixed it, thanks!  I had to specify the full path to my python installation of v3.11, but otherwise that fixed the issue.
